development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fire_dampers_dev
  schema_search_path: 'public'
  pool: 5
  username: postgres

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fire_dampers_test
  schema_search_path: 'public'
  pool: 5
  username: postgres


production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fire_dampers_prod
  schema_search_path: 'public'
  pool: 5
  username: postgres
